# Generated by Django 5.2.6 on 2025-10-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
